api/urls.py
from django.urls import path
from api.views import EntryView, EntryArrayView, EntryTestView, entries_data, get_photo, settings_data

app_name = 'api'

urlpatterns = [
    #
    path('write-data/', EntryView.as_view()),                       # POST
    path('write-array-data/', EntryArrayView.as_view()),            # POST
    path('write-client-data/', EntryTestView.as_view()),                       # POST
    path('entries-data/', entries_data, name="entries_data"),         # GET

    path('settings-data/', settings_data, name="settings_data"),         # GET

    path('photo/', get_photo, name="get_photo"),
]

cabinet/urls.py
from django.urls import path

from cabinet.views import RcLoginView, profile, RcLogoutView

app_name = 'cabinet'

urlpatterns = [
    # url(r'^$', index, name='index'),
    path('login/', RcLoginView.as_view(), name='log_in'),
    path('profile/', profile, name='profile'),
    path('logout/', RcLogoutView.as_view(), name='logout'),
]

card_index/urls.py
from django.urls import path, re_path

from card_index.views import index

app_name = 'c_index'

urlpatterns = [
    re_path(r'^$', index, name='index'),

]

django_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt
from django_site import settings
from main.views import index, robots_txt

urlpatterns = [
    path('admin/', admin.site.urls),

    re_path(r'^$', index, name='index'),

    # Cabinet
    path('lk/', include('cabinet.urls')),

    # MainApp
    path('main/', include('main.urls', namespace='main_app')),

    # API
    path('api/v1/', include('api.urls', namespace='api_app')),

    # Serv_Req
    path('s-request/', include('serv_req.urls', namespace='s_request')),

    # Card Index
    path('card-index/', include('card_index.urls', namespace='card_index')),

    # robots.txt
    re_path(r'robots.txt', robots_txt),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.views import photo_border, photo_border_ext

app_name = 'main_app'

urlpatterns = [
    path('photo-border/', photo_border, name='photo_border'),
    path('photo-border-ext/', photo_border_ext, name='photo_border_ext'),
]

main/models.py
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.utils import timezone
from django.contrib import admin
from cabinet.models import AdvUser


class WidthEntry(models.Model):
    # Запись данных про вес
    created = models.DateTimeField(default=timezone.now)
    value = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Значение")
    owner = models.ForeignKey(AdvUser, on_delete=models.SET_NULL, null=True, blank=True,
                              verbose_name='Чья запись')

    TYPE_ENTRY = (
        ('width', "Вес"),
        ('waist', "Талия"),
    )
    type = models.CharField(max_length=10, choices=TYPE_ENTRY, default='width', verbose_name="Тип записи")

    def pyre_dadetime(self):
        current_tz = timezone.get_current_timezone()
        local = self.created.astimezone(current_tz)
        return local.strftime("%H:%M %d/%m/%Y")

    class Meta:
        verbose_name_plural = 'Записи данных'
        verbose_name = 'Запись данных'
        ordering = ['-created']

    def __str__(self):
        return f'{self.value}'


@admin.register(WidthEntry)
class AdminWidthEntry(admin.ModelAdmin):
    list_display = ('created', 'value', 'type', 'owner')


class EventEntry(models.Model):
    # Событие
    created = models.DateTimeField(default=timezone.now)
    value = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Значение")
    owner = models.ForeignKey(AdvUser, on_delete=models.SET_NULL, null=True, blank=True,
                              verbose_name='Чья запись')
    T_IVENT = (
        ('none', 'не определено'),
        ('trenirovka', 'тренировка'),
    )

    type_event = models.CharField(max_length=20, choices=T_IVENT)

    class Meta:
        verbose_name_plural = 'События'
        verbose_name = 'Событие'
        ordering = ['-created']

    def __str__(self):
        return f'{self.value}'


@admin.register(EventEntry)
class AdminEventEntry(admin.ModelAdmin):
    list_display = ('created', 'type_event', 'value', 'owner')


class GlobalSettings(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название', default='Глобальные настройки')
    active_section = models.PositiveIntegerField(verbose_name='Активная категория фотоальбома', default=0)

    def __str__(self):
        return self.name


"""
@admin.register(GlobalSettings)
class AdminGlobalSettings(admin.ModelAdmin):
    list_display = ('name', 'pk', 'loading_products', 'viber_whatsapp', 'telegram', 'delivery')
"""


@receiver(post_save, sender=GlobalSettings)
def create_(sender, instance, created, **kwargs):
    all_set = GlobalSettings.objects.all()
    last_obj = GlobalSettings.objects.all().first()
    for item in all_set:
        if item != last_obj:
            item.delete()


@receiver(pre_save, sender=GlobalSettings)
def update_(sender, instance, **kwargs):
    all_set = GlobalSettings.objects.all()
    last_obj = GlobalSettings.objects.all().first()
    for item in all_set:
        if item != last_obj:
            item.delete()

main/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.http import require_GET

from django_site import settings
from main.services import get_sensors_data
try:
    from django_site.settings import LINES
except ImportError:
    LINES = [
        "User-Agent: *",
        "Disallow: /"
    ]


def set_additional_data(request):
    """ Указание дополнительных данных"""
    content = {
        "script_version": settings.SCRIPT_VERSION,
    }
    return content


def index(request):
    return render(request, 'index.html')


@login_required(login_url='/lk/login/')
def photo_border(request):
    context = get_sensors_data()
    return render(request, 'photo_border.html', context)


@login_required(login_url='/lk/login/')
def photo_border_ext(request):
    context = get_sensors_data()
    return render(request, 'photo_border_ext.html', context)


@require_GET
def robots_txt(request):
    return HttpResponse("\n".join(LINES), content_type="text/plain")

main/templates/base_generic.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">

    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Административный ресурс</title>
    {% endif %}
    {% if description %}
    <meta name="description" content="{{ description }}"/>
    {% else %}
    <meta name="description" content="Административный ресурс"/>
    {% endif %}
    {% load static %}
    <link rel="icon" href="{% static '/icons/favicon.ico' %}"/>

    {#<link href="{% static '/icons/favicon.png' %}" rel="shortcut icon" type="image/png">#}

    <link rel="stylesheet" href="{% static 'css/styles.css' %}?{{ script_version }}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}?{{ script_version }}">

    <!--script type="text/javascript" src="https://code.jquery.com/jquery-latest.min.js"></script-->
    <script type="text/javascript" src="{% static 'js/jquery-latest.min.js' %}"></script>

    <!--script type="text/javascript" src="{% static '/js/vue/cdn.jsdelivr.net_npm_vue@2.6.14_dist_vue.js' %}"></script-->
    <script type="text/javascript" src="{% static '/js/vue/vue.global.js' %}"></script>
    <script type="text/javascript" src="{% static '/js/vue/unpkg.com_axios@1.4.0_dist_axios.min.js' %}"></script>


</head>
<body class="page">
    {% comment %}
    <!--div class="middle-header">
      <div class="sub-middlehead">
          {% include 'include/header.html' %}
      </div>
    </div-->
    {% endcomment %}
    {% block breadcrumbs %}
    {% endblock %}
    <main class="main">
    {% block content %}
    {% endblock %}
    </main>

     <script type="text/javascript" src="{% static '/js/bootstrap.min.js' %}"></script>
    {#<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>#}


    <!-- scripts for this page-->
    {% block script %}
    {% endblock %}

</body>
</html>

main/templates/index.html
{% extends "base_generic.html" %}

{% load static %}

{% block script %}
    <script src="{% static 'js/clock.js' %}?{{ script_version }}"></script>
{% endblock %}

{% block breadcrumbs %}
{% comment %}
<div class="breadcrumbs">
    {% if user.is_authenticated %}
    <div class="breadcrumbs-text">
        Начало /
    </div>
    {% endif %}
</div>
{% endcomment %}
{% endblock %}


{% block content %}
{% if user.is_authenticated %}

<div class="row g-1 gy-0" style="color: white;">
    <div class="col-md-3 col-sm-0 col-xs-0"></div>
    <div class="col-md-6 col-sm-12 col-xs-12">

        {% if user.is_staff %}
        <a href="{% url 'c_index:index' %}" class="btn-primary-login">
            <div class="button-login-block">
                <span>Картотека</span>
            </div>
        </a>
        <a href="/admin/" class="btn-primary-login">
            <div class="button-login-block">
                <span>Админ страница</span>
            </div>
        </a>
        {% endif %}
        <a href="{% url 'cabinet:profile' %}" class="btn-primary-login">
            <div class="button-login-block">
                <span>Профиль</span>
            </div>
        </a>
        <br>
        <a href="{% url 'main_app:photo_border' %}" class="btn-primary-login">
            <div class="button-login-block">
                <span>Фоторамка</span>
            </div>
        </a>
        <a href="{% url 'main_app:photo_border_ext' %}" class="btn-primary-login">
            <div class="button-login-block">
                <span>Фоторамка с графиками</span>
            </div>
        </a>
    </div>
</div>
<hr>
<div class="row g-1 gy-0" style="color: white;">
    <div class="col-md-3 col-sm-0 col-xs-0"></div>
    <div class="col-md-6 col-sm-12 col-xs-12">
        <form action="{% url 'cabinet:logout' %}" method="post" style="float: right;">
            {% csrf_token %}
            <button  class="button-login-logout" type="submit" style="border: unset;">
                <img src="{% static '/icons/box-arrow-right.svg' %}">
                <span>Выйти</span>
            </button>
        </form>

    </div>
</div>
{% else %}
<div>
    <div class="row g-1 gy-0" style="color: white;">
        <div class="col-md-3 col-sm-0 col-xs-0"></div>
        <div class="col-md-6 col-sm-12 col-xs-12">
                <a href="{% url 'cabinet:log_in' %}" class="btn-primary-login">
                    <div class="button-login-block">
                        <img src="{% static '/icons/box-arrow-in-right.svg' %}" class="img-back-arrow"> <span>Войти</span>
                    </div>
                </a>

        </div>
    </div>
</div>
{% endif %}
{% endblock %}

main/templates/photo_border.html
{% extends "base_generic.html" %}

{% load static %}

{% block script %}
    <script src="{% static 'js/clock.js' %}?{{ script_version }}"></script>

{% endblock %}

{% block breadcrumbs %}
{% comment %}
<div class="breadcrumbs">
    {% if user.is_authenticated %}
    <div class="breadcrumbs-text">
        Начало /
    </div>
    {% endif %}
</div>
{% endcomment %}
{% endblock %}


{% block content %}
<div id="app" data-template="photo_border">
  <div class="row g-1 gy-0">
    <div :class="activeClass">  <!-- activeClass="active" устанавливаете в js c помощью vue -->
         {% for item in all_sensors %}
         <div class="value-sensor-cell">
            <div class="block-value">
                <div class="entry-value" data-id="{{ item.uid }}">{# item.last_entry|floatformat:"-1" #}</div>
                <div class="entry-name">{{ item.name }}</div>
            </div>
         </div>
         {% endfor %}
    </div>

    <div :class="activeAddColClass">
        <div class="block-value dateTimeValue">
            <div style="">
                <div id="clock" :class="clockClass" data-url="{% url 'api:entries_data' %}" style="float: left;font-size: 35pt;"
                data-photo-url="{% url 'api:get_photo' %}"
                ></div>
                <div id="dateClock" :class="DateClockClass" style="padding: 6px 20px;"></div>
                <!--div class="c-ring" style="width: auto;position: absolute;">
                    <svg height="20" width="20">
                       <circle cx="10" cy="10" r="6" style="fill:#000 ; stroke-width:3; stroke:#1dcfd6; fill-opacity:0.7" />
                    </svg>
                </div-->

                <div class="button-block">
                    {% comment %}
                    {% if user.is_authenticated %}
                    <form action="{% url 'cabinet:logout' %}" method="post" style="float: right;">
                       {% csrf_token %}
                        <button  class="button-login-logout" type="submit" style="border: unset;">
                            <img src="{% static '/icons/box-arrow-right.svg' %}">
                        </button>
                    </form>
                    {% else %}
                    <a href="{% url 'cabinet:log_in' %}">
                        <div class="button-login-logout" style="">
                            <img src="{% static '/icons/box-arrow-in-right.svg' %}">
                        </div>
                    </a>
                    {% endif %}

                    <div class="button-login-logout" @click="changeModePage()">
                            <img src="{% static '/icons/grid.svg' %}">
                    </div>
                    <div style="clear:both;"></div>
                    {% endcomment %}
                    <div class="button-login-logout" @click="reloadAllPhoto()">
                        <img src="{% static '/icons/arrow-clockwise.svg' %}">
                    </div>
                </div>
            </div>
        </div>

        <div class="blockPhotoPlace" id="photoPlace">
           <img v-for="(item, key) in all_photo" :src="item.img" :id="'photo-'+ key" loading="lazy" :class="item.class">
            <div class="button-switch-photo button-left" @click="switchPhotoToLeft()"></div>
            <div class="button-switch-photo button-right" @click="switchPhotoToRight()"></div>
        </div>

    </div>
  </div>
</div>
<div class="row g-1 gy-0" style="color: white;">
    <div class="col-md-3 col-sm-0 col-xs-0"></div>
    <div class="col-md-6 col-sm-12 col-xs-12">
        <a href="/" class="btn-primary-login">
            <div class="button-login-block">
                <span>На главную</span>
            </div>
        </a>
    </div>
</div>

<script type="text/javascript" src="{% static '/js/vue/app_photo_border_ext.js' %}?{{ script_version }}"></script>

{% endblock %}

main/templates/photo_border_ext.html
{% extends "base_generic.html" %}

{% load static %}

{% block script %}
<script src="{% static 'js/clock.js' %}?{{ script_version }}"></script>
{% endblock %}

{% block breadcrumbs %}
{% comment %}
<div class="breadcrumbs">
    {% if user.is_authenticated %}
    <div class="breadcrumbs-text">
        Начало /
    </div>
    {% endif %}
</div>
{% endcomment %}
{% endblock %}


{% block content %}
<div id="app" data-template="photo_border_ext">
    <div class="row g-1 gy-0">
        <div :class="activeClass">
            {% for item in all_sensors %}
            <div class="ext-sensor-block-value">
                <div class="value-sensor-cell value-sensor-ext-cell">
                    <div class="block-value block-ext-value">
                        <div class="entry-value" data-id="{{ item.uid }}">{# item.last_entry|floatformat:"-1" #}</div>
                        <div><small>{{ item.name }}</small></div>

                    </div>
                </div>
                <div class="block-iframe-value">
                    {{ item.iframe|safe }}
                </div>
                <div style="clear:both;"></div>
                <!--div class="c-ring" style="position: absolute;right: 5px;width: auto;top: 5px;">
                    <svg height="20" width="20">
                        <circle cx="10" cy="10" r="6" style="fill:#000 ; stroke-width:3; stroke:#1dcfd6; fill-opacity:0.7" />
                    </svg>
                </div-->
                <!--div class="cut-down" style="width: 34px;"></div-->
            </div>
            {% endfor %}
        </div>

        <div :class="activeAddColClass">
            <div class="block-value" style="height: 222px;position: relative;">
                <div :class="blockDateTimeClass">
                    <div id="clock" :class="clockClass" data-url="{% url 'api:entries_data' %}" @click="switchToShowButtonMode()"
                         data-photo-url="{% url 'api:get_photo' %}">
                    </div>
                    <div id="dateClock" :class="DateClockClass"></div>
                    <!--div class="c-ring" style="width: auto;position: absolute;">
                        <svg height="20" width="20">
                           <circle cx="10" cy="10" r="6" style="fill:#000 ; stroke-width:3; stroke:#1dcfd6; fill-opacity:0.7" />
                        </svg>
                    </div-->
                    <div></div>
                    <div :class="blockButtonsClass">
                        {% comment %}
                        {% if user.is_authenticated %}
                        <!--form action="{% url 'cabinet:logout' %}" method="post" style="float: right;">
                            {% csrf_token %}
                            <button  class="button-login-logout" type="submit" style="border: unset;">
                                <img src="{% static '/icons/box-arrow-right.svg' %}">
                            </button>
                        </form>
                        {% else %}
                        <a href="{% url 'cabinet:log_in' %}">
                            <div class="button-login-logout" style="">
                                <img src="{% static '/icons/box-arrow-in-right.svg' %}">
                            </div>
                        </a-->
                        {% endif %}
                        {% endcomment %}
                        <div class="button-common-control" @click="switchToHideButtonMode()">
                            <img src="{% static '/icons/x-lg.svg' %}">
                        </div>
                        <div class="button-common-control">
                            <a href="/"><img src="{% static '/icons/house.svg' %}"></a>
                        </div>
                        <div class="button-common-control" @click="changeModePage()">
                            <img src="{% static '/icons/grid.svg' %}">
                        </div>
                        <div class="button-common-control" @click="reloadAllPhoto()">
                            <img src="{% static '/icons/arrow-clockwise.svg' %}">
                        </div>
                        <div style="clear:both;"></div>
                    </div>
                </div>
            </div>
            <div class="blockPhotoPlace blockExtPhotoPlace" id="photoPlace">
                <img v-for="(item, key) in all_photo" :src="item.img" :id="'photo-'+ key" loading="lazy" :class="item.class">
                <div class="button-switch-photo button-left" @click="switchPhotoToLeft()"></div>
                <div class="button-switch-photo button-right" @click="switchPhotoToRight()"></div>
            </div>

        </div>
    </div>
</div>

<script type="text/javascript" src="{% static '/js/vue/app_photo_border_ext.js' %}?{{ script_version }}"></script>

{% endblock %}